// packages/vue-airform/index.vue
<template>
  <form action="https://airform.io/" method="post">
  </form>
</template>

<script lang="ts">
import Vue from 'vue'

type AirformInterface = {
  email?: string
} & Pick<
  React.FormHTMLAttributes<HTMLFormElement>,
  Exclude<keyof React.FormHTMLAttributes<HTMLFormElement>, 'action' | 'method'>
>

export default <AirformInterface>Vue.extend({
})
</script>

// packages/react-airform/index.tsx
import * as React from 'react'

type AirformInterface = {
  email?: string
} & Pick<
  React.FormHTMLAttributes<HTMLFormElement>,
  Exclude<keyof React.FormHTMLAttributes<HTMLFormElement>, 'action' | 'method'>
>

type FormProps = React.ComponentPropsWithoutRef<'form'>

const Airform = React.forwardRef<HTMLFormElement, FormProps>(
  (props: AirformInterface, ref) => (
    <form
      {...props}
      action={`https://airform.io/${props.email || ''}`}
      ref={ref}
      method="post"
    />
  ),
)

Airform.displayName = 'Airform'

export default Airform
