// packages/vue-airform/index.vue
<template>
  <form action="https://airform.io/" method="post">
  </form>
</template>

<script lang="ts">
import Vue from 'vue'

type AirformInterface = {
  email?: string
} & Pick<
  React.FormHTMLAttributes<HTMLFormElement>,
  Exclude<keyof React.FormHTMLAttributes<HTMLFormElement>, 'action' | 'method'>
>

export default <AirformInterface>Vue.extend({
})
</script>

// packages/angular-airform/index.ts
import { Component, Input } from '@angular/core'

// export type AirformInterface = {
//   email?: string
// } & Pick<
//   Angular.FormHTMLAttributes<HTMLFormElement>,
//   Angular.FormHTMLAttributes<HTMLFormElement>, 'action' | 'method'>
// >

@Component({
  selector: 'airform',
  template: `
    <form [action]="'https://airform.io/' + email" method="post">
      <ng-content></ng-content>
    </form>
  `,
})
export class AirformComponent {
  @Input()
  email: String = 'your@gmail.com'
}
